INSERT INTO SkinHolderDB.items (nombre, hashnamesteam, gamerpaynombre) VALUES
	('Chroma Case', 'Chroma%20Case', 'Chroma Case')
	('Chroma 2 Case', 'Chroma%202%20Case', 'Chroma 2 Case')
	('Chroma 3 Case', 'Chroma%203%20Case', 'Chroma 3 Case')
	('Clutch Case', 'Clutch%20Case', 'Clutch Case'),
	('CS20 Case', 'CS20%20Case', 'CS20 Case'),
	('CS:GO Weapon Case', 'CS%3AGO%20Weapon%20Case', 'CS:GO Weapon Case'),
	('CS:GO Weapon Case 2', 'CS%3AGO%20Weapon%20Case%202', 'CS:GO Weapon Case 2'),
	('CS:GO Weapon Case 3', 'CS%3AGO%20Weapon%20Case%203', 'CS:GO Weapon Case 3'),
	('Danger Zone Case', 'Danger%20Zone%20Case', 'Danger Zone Case'),
	('Dreams & Nightmares Case', 'Dreams%20%26%20Nightmares%20Case', 'Dreams & Nightmares Case'),
	('eSports 2013 Case', 'eSports%202013%20Case', 'eSports 2013 Case'),
	('eSports 2013 Winter Case', 'eSports%202013%20Winter%20Case', 'eSports 2013 Winter Case'),
	('eSports 2014 Summer Case', 'eSports%202014%20Summer%20Case', 'eSports 2014 Summer Case'),
	('Falchion Case', 'Falchion%20Case', 'Falchion Case'),
	('Fracture Case', 'Fracture%20Case', 'Fracture Case'),
	('Gamma Case', 'Gamma%20Case', 'Gamma Case'),
	('Gamma 2 Case', 'Gamma%202%20Case', 'Gamma 2 Case'),
	('Glove Case', 'Glove%20Case', 'Glove Case'),
	('Horizon Case', 'Horizon%20Case', 'Horizon Case'),
	('Huntsman Weapon Case', 'Huntsman%20Weapon%20Case', 'Huntsman Weapon Case'),
	('Operation Bravo Case', 'Operation%20Bravo%20Case', 'Operation Bravo Case'),
	('Operation Breakout Weapon Case', 'Operation%20Breakout%20Weapon%20Case', 'Operation Breakout Weapon Case'),
	('Operation Broken Fang Case', 'Operation%20Broken%20Fang%20Case', 'Operation Broken Fang Case'),
	('Operation Hydra Case', 'Operation%20Hydra%20Case', 'Operation Hydra Case'),
	('Operation Phoenix Weapon Case', 'Operation%20Phoenix%20Weapon%20Case', 'Operation Phoenix Weapon Case'),
	('Operation Riptide Case', 'Operation%20Riptide%20Case', 'Operation Riptide Case'),
	('Operation Vanguard Weapon Case', 'Operation%20Vanguard%20Weapon%20Case', 'Operation Vanguard Weapon Case'),
	('Operation Wildfire Case', 'Operation%20Wildfire%20Case', 'Operation Wildfire Case'),
	('Prisma Case', 'Prisma%20Case', 'Prisma Case'),
	('Prisma 2 Case', 'Prisma%202%20Case', 'Prisma 2 Case'),
	('Revolver Case', 'Revolver%20Case', 'Revolver Case'),
	('Shadow Case', 'Shadow%20Case', 'Shadow Case'),
	('Shattered Web Case', 'Shattered%20Web%20Case', 'Shattered Web Case'),
	('Snakebite Case', 'Snakebite%20Case', 'Snakebite Case'),
	('Spectrum Case', 'Spectrum%20Case', 'Spectrum Case'),
	('Spectrum 2 Case', 'Spectrum%202%20Case', 'Spectrum 2 Case'),
	('Winter Offensive Weapon Case', 'Winter%20Offensive%20Weapon%20Case', 'Winter Offensive Weapon Case');